Repository sanders41/weather-command, pull requests merged in 2023-03, with the labels that each got.

#371 Bump mypy from 1.0.1 to 1.1.1
  poetry.lock
  pyproject.toml
  tests/test_builder.py
  weather_command/_cache.py
Labels: skip-changelog, dependencies

#382 Use ruff for import sorting and remove isort
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
Labels: skip-changelog, dependencies

#384 Updated CONTRIBUTE.md
  CONTRIBUTING.md
Labels: skip-changelog

#385 Preload weather into cache when using zip
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_builder.py
  tests/test_main.py
  tests/test_weather.py
  weather_command/_builder.py
  weather_command/_utils.py
  weather_command/_weather.py
  weather_command/main.py
Labels: feature

#386 Bump version for release
  pyproject.toml
  weather_command/main.py
Labels: skip-changelog

#387 Fix version number
  pyproject.toml
  weather_command/main.py
Labels: skip-changelog
